name: CI

run-name: ${{ github.actor }}-<Module_Name-Version>

on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: mlops

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: dockerlogin
        run: echo ${{ secrets.DOCKER_USERNAME }}

      - name: dockerpass
        run: echo ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t <repo-name>/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: docker push <repo-name>/${{ env.IMAGE_NAME }}:${{ github.sha }}
